# Generated by Django 4.1.1 on 2022-10-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JUSTDOGS', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dogname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
